### PR TITLE
adds DPRS, SPSW and TDSW

### PR DESCRIPTION
**Pull request by blip2**
added additional sensors as per #223

### CODE REVIEW

**Review by RitaLav — CHANGES_REQUESTED** [review]
Could the DPRS description change to ' differential pressure sensor' instead of 'differential pressure switch'?

**Comment by blip2** [comment]
@RitaLav these are two different physical things (switch = boolean, sensor = analog value) do we add both?

**Comment by RitaLav** [comment]
Sensor and switch can both be added with separate abbreviations.

DPRSW (actuator - differential pressure switch) already exists in the register (so we don't need to add another one), the sensor does not.

**Comment by RitaLav** [comment]
one more comment added to issue #223 which concludes all abbreviations requested

**Review by RitaLav — CHANGES_REQUESTED** [review]
We believe the switches should be best classified as switches (since you note on the issue that have normally open and closed states.

Therefore changes as follows (first item remains unchanged)

sensor - differential pressure sensor,DPRS,SENSOR,IfcSensor,PRESSURESENSOR
actuator - pressure switch,PRSW, ,IfcActuator,NOTDEFINED
actuator - static pressure switch, ,IfcActuator,NOTDEFINED
actuator - thermal dispersion flow proving switch,TDSW, ,IfcActuator,NOTDEFINED

Is that a correct interpretation?

**Comment by blip2** [comment]
hi Rita, I don't feel any of those should be classed as an actuator. An actuator would normally be an output device, not an input.

I would say DPRSW is wrong - maybe added as a sensor for an actuator? but a differential pressure switch itself is a input/sensor.

**Comment by jgunstone** [comment]
hi - 
I was just about to add `PRSW` but I'm still a bit confused...

to my logic: 
sensors (IfcSensor) reads info i.e. pressure for a system
switches / actuators (IfcSwitchingDevice, IfcActuator) provides action. 

actuators / switches provide fundamentally the same function but are for mechanical / electrical action respectively.
 
I agree with @blip2 that this is in wrong:
image
I think its incorrectly listed as an IfcActuator despite explicitly being called a switch in the description. proposee the following change:

`switch - differential pressure,DPRSW,,IfcSwitchingDevice,NOTDEFINED`
e.g. 
https://www.wika.com/en-gb/psd_4.WIKA
both senses, and switches (digital and analogue outputs available) but does not actuate. 

then if we add the other switches i'd suggest: 
`switch - absolute pressure,PRSW, ,IfcSwitchingDevice,NOTDEFINED`
`switch - static pressure,SPRSW ,IfcSwitchingDevice,NOTDEFINED`

**Comment by RitaLav** [comment]
Thank you @blip2 @jgunstone 

Conclusion:

Will add:
sensor - differential pressure sensor,DPS,SENSOR,IfcSensor,PRESSURESENSOR
switch - differential pressure,DPSW,,IfcSwitchingDevice,NOTDEFINED
switch - absolute pressure,APSW, ,IfcSwitchingDevice,NOTDEFINED
switch - static pressure,SPSW, ,IfcSwitchingDevice,NOTDEFINED
switch - thermal dispersion flow proving switch,TDSW, ,IfcSwitchingDevice,NOTDEFINED

We will also need to amend the existing dew point switch abbreviation from 'DPSW' to 'DEWSW' and modify its ifc class to IfcSwitchingDevice

**Comment by blip2** [comment]
rebased due to major changes in master branch. should be good to go now.

**Review by RitaLav — APPROVED** [review]

**Comment by RitaLav** [comment]
Thank you @blip2 - all done

**Pull request merged**
