### PR TITLE
Adding (Li-ion) cell

### PR DESCRIPTION
**Pull request by darshanjain12**
Adding (Li-ion) cell

### CODE REVIEW

**Comment by RitaLav** [comment]
@darshanjain12 please create an issue associated with the PR.

**Comment by TheFridgeShaman** [comment]
Hi, please could you add the "can_be_connected" information at the end of the line?
e.g.:
lithium ion cell,LIIONC,,IfcElectricAppliance,NOTDEFINED,0
or
lithium ion cell,LIIONC,,IfcElectricAppliance,NOTDEFINED,1

Please could you clarify why lightning protection - earthing tape went from being not connected to connected (0 at the end of line 444 changed to 1)?

Thank you very much.

**Comment by darshanjain12** [comment]
> Hi, please could you add the "can_be_connected" information at the end of the line? e.g.: lithium ion cell,LIIONC,,IfcElectricAppliance,NOTDEFINED,0 or lithium ion cell,LIIONC,,IfcElectricAppliance,NOTDEFINED,1
> 
> Please could you clarify why lightning protection - earthing tape went from being not connected to connected (0 at the end of line 444 changed to 1)?
> 
> Thank you very much.

Done the required changes. The not connected to connected i did it by mistake

**Comment by jgunstone** [comment]
generally looks good - my comments: 

- maybe should prefix the description with "battery" so if you search for battery in the csv you find it and it appears with other batteries
image
- change the `ifc_class` class from `IfcElectricAppliance` --> `IfcElectricFlowStorageDevice`

along that same line of reasoning... could consider BATTLI as an abbreviation instead of LIIONC to match the BATT abbreviation which already exists.

**Comment by RitaLav** [comment]
issue number #271

**Review by RitaLav — APPROVED** [review]

**Pull request merged**
